
# What is the cost of passing a buffer to a function?
def ParseStudent(cur):
    line = open("Students.csv", "r")
    entry = "blah"
    shift = 0
    while len(entry) > 0:
        entry = line.readline()
        submit = entry.split(',')
        shift+=1
        if shift > 1 and shift < 1002:
            fullname = submit[0].strip()
            email = submit[1].strip()
            age = int(submit[2].strip())
            zip = int(submit[3].strip())
            phone = int(submit[4].strip())
            gender = submit[5].strip()
            city = submit[6].strip()
            state = submit[7].strip()
            password = submit[8].strip()
            street = submit[9].strip()
            major = submit[10].strip()
            # need to account for null spaces in data set
            # course1 = submit[11].strip()
            # course1name = submit[12].strip()
            # course1details = submit[13].strip()
            # course1type = submit[14].strip()
            # course1section = float(submit[15].strip())
            # course1sectionlimit = int(submit[16].strip())
            # course1hw_no = float(submit[17].strip())
            # course1hw_details = submit[18].strip()
            # course1hw_grade = float(submit[19].strip())
            # course1exam_no = float(submit[20].strip())
            # course1exam_details = submit[21].strip()
            # course1exam_grade = float(submit[22].strip())
            # course2 = submit[23].strip()
            # course2name = submit[24].strip()
            # course2details = submit[25].strip()
            # course2type = submit[26].strip()
            # course2section = float(submit[27].strip())
            # course2sectionlimit = int(submit[28].strip())
            # course2hw_no = float(submit[29].strip())
            # course2hw_details = submit[30].strip()
            # course2hw_grade = float(submit[31].strip())
            # course2exam_no = float(submit[32].strip())
            # course2exam_details = submit[33].strip()
            # course2exam_grade = float(submit[34].strip())
            # course3 = submit[35].strip()
            # course3name = submit[36].strip()
            # course3details = submit[37].strip()
            # course3type = submit[38].strip()
            # course3section = float(submit[39].strip())
            # course3sectionlimit = int(submit[40].strip())
            # course3hw_no = float(submit[41].strip())
            # course3hw_details = submit[42].strip()
            # course3hw_grade = float(submit[43].strip())
            # course3exam_no = float(submit[44].strip())
            # course3exam_details = submit[45].strip()
            # course3exam_grade = float(submit[46].strip())
            cur.execute("INSERT INTO Students (email, password, name, age, gender, major, street, zipcode) VALUES (?,?,?,?,?,?,?,?);", (email, password, fullname, age, gender, major, street, zip))
    line.close()
    return cur
